Design cinema entity
Giorno6Hackerman/Satan-tickets pull request #17
Opened 2021-02-17 11:32 UTC by Giorno6Hackerman

2021-02-17 12:33 UTC, andrei-kruhliakou-itechart requested changes

2021-02-17 12:33 UTC, andrei-kruhliakou-itechart commented on angular-satan-tickets/src/app/app.module.ts
> +    AppRoutingModule,
redundant comma

2021-02-17 12:33 UTC, andrei-kruhliakou-itechart commented on angular-satan-tickets/src/app/app.module.ts
> +    CinemaSearchComponent,
redundant comma

2021-02-17 15:05 UTC, Giorno6Hackerman commented on SatanTicketsApi/DTOs/CinemaDTO.cs
> +        public short? SitsCount { get; set; }
There will be separate entity for hall later, of course. I just tried to avoid dealing with seats, so I emulated them with count. I planned to delete them in the end and create instead hall entity with 'CinemaId' field or sth like this
Now I realize that I could just keep only name & city fields(((

2021-02-17 15:06 UTC, Giorno6Hackerman commented on SatanTicketsApi/DTOs/CinemaDTO.cs
> +        public short? SitsCount { get; set; }
I got caught up with this and forget that it's just temporary, sorry(

2021-02-17 15:08 UTC, Giorno6Hackerman commented on SatanTicketsApi/DTOs/CinemaDTO.cs
> +        public short? SitsCount { get; set; }
Yep, it should be
Now I have to replace it in the entire project((

2021-02-18 18:00 UTC, andrei-kruhliakou-itechart requested changes

2021-02-18 18:00 UTC, andrei-kruhliakou-itechart commented on SatanTicketsApi/Models/Cinema.cs
> +        public bool IsDeleted { get; set; } = false;
Why do you need default value here?

2021-02-18 18:21 UTC, Giorno6Hackerman commented on SatanTicketsApi/Models/Hall.cs
> +        public int? CinemaId { get; set; }
No, it's just RequiredAttribute doesn't work for value types. I used this for dates before

2021-02-19 09:53 UTC, andrei-kruhliakou-itechart commented on SatanTicketsApi/DTOs/HallDTO.cs
> +        public int CinemaId { get; set; }
What is the real validation for CinemaId and where it will be performed?
Does range check really make sense here?

2021-02-19 09:59 UTC, Giorno6Hackerman commented on SatanTicketsApi/DTOs/HallDTO.cs
> +        public int CinemaId { get; set; }
In DBMS)))

2021-02-19 10:50 UTC, andrei-kruhliakou-itechart approved these changes

2021-02-19 10:50 UTC, merged